// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniOps.Infrastructure.Data;

#nullable disable

namespace OmniOps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705161724_AddShipments")]
    partial class AddShipments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniOps.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedDeliveryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxSafeTempCelsius")
                        .HasColumnType("double precision");

                    b.Property<double>("MinSafeTempCelsius")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueAtRiskUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Status");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BatchNumber = "B-4471",
                            DepartedAtUtc = new DateTime(2026, 7, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 100.0,
                            MinSafeTempCelsius = 50.0,
                            ProductName = "Insulin Glargine",
                            Status = 0,
                            ValueAtRiskUsd = 12400m,
                            VehicleId = "Truck-001"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000002"),
                            BatchNumber = "HBV-0293",
                            DepartedAtUtc = new DateTime(2026, 7, 2, 6, 30, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 95.0,
                            MinSafeTempCelsius = 50.0,
                            ProductName = "Hepatitis B Vaccine",
                            Status = 0,
                            ValueAtRiskUsd = 8750m,
                            VehicleId = "Truck-002"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-0000-0000-000000000003"),
                            BatchNumber = "BCG-1182",
                            DepartedAtUtc = new DateTime(2026, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 100.0,
                            MinSafeTempCelsius = 55.0,
                            ProductName = "BCG Vaccine",
                            Status = 0,
                            ValueAtRiskUsd = 6200m,
                            VehicleId = "Truck-003"
                        });
                });

            modelBuilder.Entity("OmniOps.Core.Entities.VehicleTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EngineTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("FuelLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
