// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniOps.Infrastructure.Data;

#nullable disable

namespace OmniOps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707133936_EndgamePhases1To4")]
    partial class EndgamePhases1To4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniOps.Core.Entities.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<double>("SafetyScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Fleets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Primary pharmaceutical cold-chain fleet",
                            Name = "Cold-Chain North"
                        });
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolygonCoordinatesJson")
                        .HasColumnType("text");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("ShapeType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("Geofences");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedDeliveryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxSafeTempCelsius")
                        .HasColumnType("double precision");

                    b.Property<double>("MinSafeTempCelsius")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueAtRiskUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Status");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BatchNumber = "B-4471",
                            DepartedAtUtc = new DateTime(2026, 7, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 100.0,
                            MinSafeTempCelsius = 50.0,
                            ProductName = "Insulin Glargine",
                            Status = 0,
                            ValueAtRiskUsd = 12400m,
                            VehicleId = "Truck-001"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000002"),
                            BatchNumber = "HBV-0293",
                            DepartedAtUtc = new DateTime(2026, 7, 2, 6, 30, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 95.0,
                            MinSafeTempCelsius = 50.0,
                            ProductName = "Hepatitis B Vaccine",
                            Status = 0,
                            ValueAtRiskUsd = 8750m,
                            VehicleId = "Truck-002"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-0000-0000-000000000003"),
                            BatchNumber = "BCG-1182",
                            DepartedAtUtc = new DateTime(2026, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDeliveryUtc = new DateTime(2026, 7, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            MaxSafeTempCelsius = 100.0,
                            MinSafeTempCelsius = 55.0,
                            ProductName = "BCG Vaccine",
                            Status = 0,
                            ValueAtRiskUsd = 6200m,
                            VehicleId = "Truck-003"
                        });
                });

            modelBuilder.Entity("OmniOps.Core.Entities.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("AggregateType", "AggregateId");

                    b.ToTable("StoredEvents");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId", "Status");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InsuranceExpiryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("FleetId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            ExternalId = "Truck-001",
                            FleetId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Registration = "CC-4471",
                            Status = 0,
                            Vin = "1HGBH41JXMN109186"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000002"),
                            ExternalId = "Truck-002",
                            FleetId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Registration = "CC-0293",
                            Status = 0,
                            Vin = "1HGBH41JXMN109187"
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0000-000000000003"),
                            ExternalId = "Truck-003",
                            FleetId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Registration = "CC-1182",
                            Status = 0,
                            Vin = "1HGBH41JXMN109188"
                        });
                });

            modelBuilder.Entity("OmniOps.Core.Entities.VehicleMaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleMaintenanceRecords");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.VehicleTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("EngineTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("FuelLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("SensorReadingsJson")
                        .HasColumnType("text");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Depot", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Fleet", "Fleet")
                        .WithMany("Depots")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Driver", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Fleet", "Fleet")
                        .WithMany("Drivers")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Geofence", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Fleet", "Fleet")
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Trip", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniOps.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Driver", "AssignedDriver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniOps.Core.Entities.Fleet", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDriver");

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.VehicleMaintenanceRecord", b =>
                {
                    b.HasOne("OmniOps.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Fleet", b =>
                {
                    b.Navigation("Depots");

                    b.Navigation("Drivers");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("OmniOps.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("MaintenanceHistory");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
