{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "omniops.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "omniops.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "omniops.selectorLabels" . | nindent 6 }}
{{- end }}
